[server]
port = 8501
address = "0.0.0.0"
headless = true
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false

[browser]
gatherUsageStats = false
serverAddress = "rwps3tcc8n.us-east-1.awsapprunner.com"
serverPort = 443
