[server]
port = 8501
address = "0.0.0.0"
headless = true
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false

[browser]
gatherUsageStats = false
serverAddress = "tienda-retail.pocs.cni.ia.blend360.com"
serverPort = 443
